version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-test
    steps:
      - checkout
      - run:
        name: Update npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: Install npm dependencies
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules

  test:
    docker: 
      - image: circleci/node:8
    working_directory: ~/circleci-test
    steps:
      - checkout
      - run:
        name: Jest
        command: npm test

workflows:
  version: 2.1
  test_with_jest:
    jobs:
      - build
      - test:
        requires:
          - build
